<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="2" total="16" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="309" started-at="2021-05-16T20:13:06Z" finished-at="2021-05-16T20:13:07Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="309" started-at="2021-05-16T20:13:06Z" finished-at="2021-05-16T20:13:07Z">
      <class name="StringHomeTest">
        <test-method status="PASS" signature="BeforeClass()[pri:0, instance:StringHomeTest@1e643faf]" name="BeforeClass" is-config="true" duration-ms="0" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeClass -->
        <test-method status="PASS" signature="provider(int, java.lang.String)[pri:0, instance:StringHomeTest@1e643faf]" name="provider" duration-ms="1" started-at="2021-05-16T20:13:07Z" data-provider="getData" finished-at="2021-05-16T20:13:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[four]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- provider -->
        <test-method status="PASS" signature="provider(int, java.lang.String)[pri:0, instance:StringHomeTest@1e643faf]" name="provider" duration-ms="1" started-at="2021-05-16T20:13:07Z" data-provider="getData" finished-at="2021-05-16T20:13:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[6]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[six]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- provider -->
        <test-method status="PASS" signature="testFormat()[pri:0, instance:StringHomeTest@1e643faf]" name="testFormat" duration-ms="2" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFormat -->
        <test-method status="FAIL" signature="testFormat1()[pri:0, instance:StringHomeTest@1e643faf]" name="testFormat1" duration-ms="1" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Format is wrong, expected isDreamscometrue11 expected [Dreamscometrue11] but found [Dreamscometrue]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Format is wrong, expected isDreamscometrue11 expected [Dreamscometrue11] but found [Dreamscometrue]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at StringHomeTest.testFormat1(StringHomeTest.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFormat1 -->
        <test-method status="PASS" signature="AfterClass()[pri:0, instance:StringHomeTest@1e643faf]" name="AfterClass" is-config="true" duration-ms="0" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterClass -->
      </class> <!-- StringHomeTest -->
      <class name="MathoperationsTest">
        <test-method status="PASS" signature="BeforeSuite()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="BeforeSuite" is-config="true" duration-ms="38" started-at="2021-05-16T20:13:06Z" finished-at="2021-05-16T20:13:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeSuite -->
        <test-method status="PASS" signature="BeforeClass()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="BeforeClass" is-config="true" duration-ms="2" started-at="2021-05-16T20:13:06Z" finished-at="2021-05-16T20:13:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeClass -->
        <test-method status="PASS" signature="test2()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="test2" duration-ms="78" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="BeforeMethod" is-config="true" duration-ms="0" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="AfterMethod" is-config="true" duration-ms="5" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="BeforeMethod" is-config="true" duration-ms="4" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="PASS" signature="testEqual()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="testEqual" duration-ms="3" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEqual -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="AfterMethod" is-config="true" duration-ms="0" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="BeforeMethod" is-config="true" duration-ms="0" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="PASS" signature="testEqual1()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="testEqual1" duration-ms="1" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEqual1 -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="AfterMethod" is-config="true" duration-ms="0" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="BeforeMethod" is-config="true" duration-ms="0" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="testEqual2()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="testEqual2" duration-ms="2" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at MathoperationsTest.testEqual2(MathoperationsTest.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEqual2 -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="AfterMethod" is-config="true" duration-ms="10" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="BeforeMethod" is-config="true" duration-ms="1" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="PASS" signature="testMax()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="testMax" duration-ms="0" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMax -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="AfterMethod" is-config="true" duration-ms="1" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="BeforeMethod" is-config="true" duration-ms="3" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="testMax1()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="testMax1" duration-ms="2" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [17] but found [15]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [17] but found [15]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at MathoperationsTest.testMax1(MathoperationsTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMax1 -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="AfterMethod" is-config="true" duration-ms="1" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="BeforeMethod" is-config="true" duration-ms="0" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="PASS" signature="testMin()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="testMin" duration-ms="1" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMin -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="AfterMethod" is-config="true" duration-ms="2" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="BeforeMethod" is-config="true" duration-ms="1" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="testMin1()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="testMin1" duration-ms="1" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-9] but found [-98]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-9] but found [-98]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at MathoperationsTest.testMin1(MathoperationsTest.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMin1 -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="AfterMethod" is-config="true" duration-ms="65" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="testSquareRoot()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="testSquareRoot" duration-ms="1" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSquareRoot -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="BeforeMethod" is-config="true" duration-ms="0" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="AfterMethod" is-config="true" duration-ms="1" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="BeforeMethod" is-config="true" duration-ms="5" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="testSquareRoot1()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="testSquareRoot1" duration-ms="1" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [12.0] but found [11.832159566199232]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [12.0] but found [11.832159566199232]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at MathoperationsTest.testSquareRoot1(MathoperationsTest.java:98)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSquareRoot1 -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="AfterMethod" is-config="true" duration-ms="0" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="AfterClass()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="AfterClass" is-config="true" duration-ms="0" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterClass -->
        <test-method status="PASS" signature="AfterSuite()[pri:0, instance:MathoperationsTest@3b6eb2ec]" name="AfterSuite" is-config="true" duration-ms="1" started-at="2021-05-16T20:13:07Z" finished-at="2021-05-16T20:13:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterSuite -->
      </class> <!-- MathoperationsTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
